
image: attensee/s3_website

pipelines:
  default:
    - step:
        script: 
          - apt-get update
          - apt-get install zip
          - cd src
          - zip -r ../zipped/Hello.zip .
          - s3_website push