
image: attensee/s3_website

pipelines:
  default:
    - step:
        script: 
          - apt-get update
          - apt-get install zip
          - zip -r zipped/Hello.zip src/*
          - s3_website push